services:
  mcp:
    build:
      context: .
      dockerfile: ./mcp/Dockerfile
    container_name: mcp
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - ENV=production
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./demo_cases:/app/demo_cases 